---
name: Ansible Integration Test
on:  # yamllint disable-line rule:truthy
  pull_request:
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  ansible_integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: Update pip, git
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install podman

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: ansible_collections/cloud/vmware_ops

      - name: Install requirements
        run: |
          ansible-galaxy collection install -r requirements.yml
        working-directory: ansible_collections/cloud/vmware_ops

      - name: Install python packages from requirements txt file
        run: |
          pip3 install -r requirements.txt
        working-directory: ansible_collections/cloud/vmware_ops

      - name: Run
        run: |
          ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python make integration
        working-directory: ansible_collections/cloud/vmware_ops
